# Generated by Django 4.2.11 on 2024-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_sale_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
    ]
